### 1) Импорт библиотеки NumPy с общепринятым сокращением.

In [ ]:
import numpy as np

### 2) Примеры создания массивов:

In [22]:
# массив из обычного списка
nums_array = np.array([1, 2, 3]) 
nums_array

array([1, 2, 3])

In [21]:
# массив из нулей
zeros_array = np.zeros(8)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
# массив из едениц
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
# массив из цифр (от 0 до 9)
nums_arange = np.arange(10)
nums_arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3) Демонстрация атрибутов:

In [27]:
# вывод формы (shape)
nums_arange.shape

(10,)

In [28]:
# вывод ипа данных (dtype)
nums_arange.dtype

dtype('int64')

### 4) Примеры индексирования и срезов:

In [31]:
# получение отдельного элемента
nums_arange[4]

np.int64(4)

In [34]:
# извлечение подмассива с помощью среза
nums_arange[2:7]

array([2, 3, 4, 5, 6])

### 5) Примеры векторных операций и базовых статистик:

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [41]:
# поэлементное сложение
a+b

array([5, 7, 9])

In [42]:
# поэлементное умножение массивов
a*b

array([ 4, 10, 18])

In [44]:
# вычисление средней величины (mean) 
(a+b).mean()

np.float64(7.0)